import { Icon } from '@iconify/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Button from '../../components/Button';
import Cta from '../../components/Cta';
import Div from '../../components/Div';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import SectionHeading from '../../components/SectionHeading';
import Spacing from '../../components/Spacing';
import ContactInfoWidget from '../../components/Widget/ContactInfoWidget';

export default function PortfolioDetails() {
  const router = useRouter();
  const careerId = router.query.careerId;
  return (
    <>
      <Head>
        <title>{careerId}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Work With Us"
          bgSrc="/images/service_hero_bg.jpeg"
          pageLinkText={careerId}
        />
        <Spacing lg="150" md="80" />
        <Div className="container">
          {/* <img
            src="/images/portfolio_details_1.jpeg"
            alt="Details"
            className="cs-radius_15 w-100"
          /> */}
          <Spacing lg="90" md="40" />
          <Div className="row">
            <Div className="col-lg-6">
              <SectionHeading title="Front End Developer" subtitle="On-Site | Contract-Based | Part-Time">
                <Spacing lg="40" md="20" />
                <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                  Description
                </h3>
                <Spacing lg="10" md="10" />
                <p>
                Această poziție presupune dezvoltarea 
                și personalizarea de cabine foto virtuale 
                respectând cerințele clienților. De asemenea, 
                poziția presupune dezvoltarea de noi pagini web
                 pentru site-ul de prezentare care este realizat în WordPress.
                </p>
                <Spacing lg="10" md="10" />
                <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                  Description
                </h3>
                <Spacing lg="10" md="10" />
                <ul>
                  <li> Dezvoltarea cabinelor foto virtuale respectând indicațiile primite din partea clienților.</li>
                  <li>Personalizarea portalelor de client pentru fiecare cabină foto virtuală utilizând HTML/CSS/Javascrip</li>
                  <li>Testarea cabinelor foto virtuale.</li>
                  <li>Dezvoltarea de noi pagini web pentru site-ul de prezentare.</li>
                </ul>
              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-lg-1">
              <Spacing lg="60" md="40" />
              <h2 className="cs-font_30 cs-font_26_sm cs-m0">Project Info -</h2>
              <Spacing lg="50" md="30" />
              <Div className="row">
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Javascript
                  </h3>
                  {/* <p className="cs-m0">Artwork</p>
                  <Spacing lg="30" md="30" /> */}
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Html
                  </h3>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    CSS
                  </h3>
                  <Spacing lg="30" md="30" />
                  </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    WordPress
                  </h3>
                  {/* <p className="cs-m0">14-Aug-2022</p> */}
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Engleza
                  </h3>
                  {/* <p className="cs-m0">Andreo Bowla</p> */}
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Photoshop
                  </h3>
                  {/* <p className="cs-m0">Andreo Bowla</p> */}
                  <Spacing lg="30" md="30" />
                </Div>
              </Div>
            </Div>
          </Div>
          <Spacing lg="65" md="10" />
          <Div className="cs-page_navigation cs-center">
            <Div>
              <Button
                btnLink="/portfolio/portfolio-details"
                btnText="Prev Job"
                variant="cs-type1"
              />
            </Div>
            <Div>
              <Button
                btnLink="/portfolio/portfolio-details"
                btnText="Next Job"
              />
            </Div>
          </Div>
        </Div>
            {/* Form start */}
           
        {/* </Div> */}
        <Spacing lg="145" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-lg-6">
              <SectionHeading
                title="GET YOUR DREAM JOB"
                subtitle="Getting Touch"
              />
              <Spacing lg="55" md="30" />
              <ContactInfoWidget withIcon />
              <Spacing lg="0" md="50" />
            </Div>
            <Div className="col-lg-6">
              <form action="#" className="row">
                <Div className="col-sm-6">
                  <label className="cs-primary_color">Full Name*</label>
                  <input type="text" className="cs-form_field" />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-6">
                  <label className="cs-primary_color">Email*</label>
                  <input type="text" className="cs-form_field" />
                  <Spacing lg="20" md="20" />
                </Div>
                {/* <Div className="col-sm-6">
                  <label className="cs-primary_color">Project Type*</label>
                  <input type="text" className="cs-form_field" />
                  <Spacing lg="20" md="20" />
                </Div> */}
                <Div className="col-sm-6">
                  <label className="cs-primary_color">Mobile*</label>
                  <input type="text" className="cs-form_field" />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-6">
                  <label className="cs-primary_color">Upload CV</label>
                  <input type="file" className="cs-form_field" />
                  <Spacing lg="20" md="20" />
                </Div>
                <Div className="col-sm-12">
                  <label className="cs-primary_color">Mobile*</label>
                  <textarea
                    cols="30"
                    rows="7"
                    className="cs-form_field"
                  ></textarea>
                  <Spacing lg="25" md="25" />
                </Div>
                <Div className="col-sm-12">
                  <button className="cs-btn cs-style1">
                    <span>Apply</span>
                    <Icon icon="bi:arrow-right" />
                  </button>
                </Div>
              </form>
            </Div>
          </Div>
        </Div>
         {/* Form End */}
        <Spacing lg="145" md="80" />
        <Cta
          title="agency@arino.com"
          bgSrc="/images/cta_bg_2.jpeg"
          variant="rounded-0"
        />
      </Layout>
    </>
  );
}

