import Head from 'next/head';
import React from 'react';
import Card from '../../components/Card';
import Cta from '../../components/Cta';
import Div from '../../components/Div';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import PricingTableList from '../../components/PricingTable/PricingTableList';
import SectionHeading from '../../components/SectionHeading';
import TestimonialSlider from '../../components/Slider/TestimonialSlider';
import Spacing from '../../components/Spacing';
import JobList from '../../components/JobList';

export default function Career() {
  return (
    <>
      <Head>
        <title>Career</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Careers"
          bgSrc="images/service_hero_bg.jpeg"
          pageLinkText="Careers"
        />
        <Spacing lg="100" md="80" />
        
        <Div className="cs-shape_wrap_4">

          <Div className="cs-shape_4"></Div>
          <Div className="cs-shape_4"></Div>
          <Div className="container">
          <SectionHeading
                  title="Opening Positions"
                  subtitle="We support the growth of tomorrow’s bright minds in this field by building a bridge between our organisation and the technical universities through Internship & Graduates programmes, student competitions and dedicated events"
                  btnText=""
                  btnLink="/service"
                  variant={"cs-style3 text-center"}
                />
                <Spacing lg="50" md="80" />
          <JobList/>
          </Div>
        </Div>
       
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            // bgSrc="/images/cta_bg.jpeg"
            bgSrc="/images/cta/a.png"
          />
        </Div>
      </Layout>
    </>
  );
}
