import { Icon } from '@iconify/react';
import Head from 'next/head';
import React from 'react';
import Div from '../../components/Div';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import SectionHeading from '../../components/SectionHeading';
import Spacing from '../../components/Spacing';
import ContactInfoWidget from '../../components/Widget/ContactInfoWidget';
import OurProcess from "../../components/OurProcess"

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Contact Us"
          bgSrc="/images/contact_hero_bg.jpeg"
          pageLinkText="Contact"
        />
        <Spacing lg="150" md="80" />
        <Div className="container">
          
            <OurProcess/>

            

        </Div>
        
      </Layout>
    </>
  );
}
