import Head from 'next/head';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import FunFact from '../components/FunFact';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import TeamSlider from '../components/Slider/TeamSlider';
import Spacing from '../components/Spacing';

export default function About() {
  const funfaceData = [
    {
      title: 'Global Happy Clients',
      factNumber: '40K',
    },
    {
      title: 'Project Completed',
      factNumber: '50K',
    },
    {
      title: 'Team Members',
      factNumber: '245',
    },
    {
      title: 'Digital products',
      factNumber: '550',
    },
  ];
  return (
    <>
      <Head>
        <title>Home - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Page Heading Section */}
        <PageHeading
          title="All about good people & smart projects"
          subtitle="We work together to design and develop software that we are proud of"
          bgSrc="images/about_hero_bg.jpeg"
          pageLinkText="About Us"
        />
        {/* End Page Heading Section */}

        {/* Start About Section */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="Our Mission"
                subtitle="About Our Agency"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                Our mission is to enhance business growth of our customers 
                with creative design, development and to deliver market 
                defining high quality solutions that create value and 
                reliable competitive advantage to customers around the globe.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-xl-2">
              <img
                src="/images/aboutImages/a.jpg"
                alt="About"
                className="w-100 cs-radius_15 "
              />
              <Spacing lg="25" md="25" />
            </Div>
            <Div className="col-lg-7">
              <img
                src="/images/aboutImages/c.jpg"
                alt="About"
                className="w-100 cs-radius_15 cover-image"
              />
              <Spacing lg="25" md="25" />
            </Div>
            <Div className="col-lg-5">
              <img
                src="/images/aboutImages/b.jpg"
                alt="About"
                className="w-100 cs-radius_15 cover-image"
              />
              <Spacing lg="25" md="25" />
            </Div>
          </Div>
        </Div>
        <Spacing lg="75" md="55" />
        {/* End About Section */}

        {/* Start Fun Fact Section */}
        <Div className="container">
          <FunFact
            title="Our fun fact"
            subtitle="Sed ut perspiciatis unde omnis iste natus error voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis."
            data={funfaceData}
          />
        </Div>
        {/* End Fun Fact Section */}

        {/* Start Why Choose Section */}
        <Spacing lg="100" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-image_layer cs-style1">
                <Div className="cs-image_layer_in">
                  <img
                    src="/images/aboutImages/d.jpg"
                    alt="About"
                    className="w-100 cs-radius_15 cover-image squareAR"
                  />
                </Div>
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
            <Div className="col-xl-5 offset-xl-1 col-lg-6">
              <SectionHeading
                title="Highly experienced pepole with us"
                subtitle="Why Choose Us"
              >
                <Spacing lg="30" md="20" />
                <ul className='listStyleNone'>
                  <li>
                    <h3 className="cs-m0">Dedication</h3>
                    <p className="cs-m0">
                    We are fully committed to delivering expected results and quality service.
                    </p>
                  </li>
                  <li>
                    <h3 className="cs-m0">Knowledge</h3>
                    <p className="cs-m0">
By having a large experience in software engineering, we can choose the right methods, technologies and tools to ensure that your business needs are met.
                    </p>
                  </li>
                  <li>
                    <h3 className="cs-m0">Passionate</h3>
                    <p className="cs-m0">
                    We love developing products that change the way people do things, making life easier and more efficient.
                    </p>
                  </li>
                  <li>
                    <h3 className="cs-m0">Professional</h3>
                    <p className="cs-m0">
                    Our engineering-led approach means that our software is well-built and forms a solid, sustainable base fo the success of our clients business.
                    </p>
                  </li>
                </ul>
                
                
                {/* <p className="cs-m0">
                  This is the main factor that sets us apart from our
                  competition and allows us to deliver a specialist business
                  consultancy service. Our team applies its wide-ranging
                  experience to determining. Through our years of experience,
                  we’ve also learned that while each channel.
                </p>
                <Spacing lg="15" md="15" />
                <p className="cs-m0">
                  This is the main factor that sets us apart from our
                  competition and allows us to deliver a specialist business
                  consultancy service. Our team applies its wide-ranging
                  experience to determining.
                </p> */}
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="0" />
              </SectionHeading>
            </Div>
          </Div>
        </Div>
        {/* End Why Choose Section */}

        {/* Start Team Section */}
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading
            title="Awesome team <br/>members"
            subtitle="Our Team"
            variant="cs-style1"
          />
          <Spacing lg="85" md="45" />
          <TeamSlider />
        </Div>
        {/* End Team Section */}

        {/* Start CTA Section */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
